package com.example.recognizeai

import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import com.example.recognizeai.databinding.ActivityTermsOfServiceBinding
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject
import java.util.concurrent.TimeUnit

class TermsOfServiceActivity : AppCompatActivity() {

    private lateinit var binding: ActivityTermsOfServiceBinding

    private val client = OkHttpClient.Builder()
        .connectTimeout(10, TimeUnit.SECONDS)
        .readTimeout(10, TimeUnit.SECONDS)
        .build()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityTermsOfServiceBinding.inflate(layoutInflater)
        setContentView(binding.root)

        binding.btnBack.setOnClickListener { finish() }

        val langCode = LocaleHelper.getCurrentLanguageCode()
        loadTerms(langCode)
    }

    private fun loadTerms(langCode: String) {
        val cached = getCachedTerms(langCode)
        if (cached.isNotEmpty()) {
            binding.tvTermsContent.text = cached
        }

        CoroutineScope(Dispatchers.IO).launch {
            try {
                val request = Request.Builder()
                    .url("${SessionManager.BASE_URL}/api/terms-of-service")
                    .get()
                    .build()
                val response = client.newCall(request).execute()
                val body = response.body?.string() ?: "{}"
                if (!response.isSuccessful) throw Exception("Server error: ${response.code}")

                val json = JSONObject(body)
                val prefs = getSharedPreferences("terms_of_service", MODE_PRIVATE)
                val editor = prefs.edit()
                val keys = json.keys()
                while (keys.hasNext()) {
                    val key = keys.next()
                    editor.putString(key, json.optString(key, ""))
                }
                editor.apply()

                val terms = json.optString(langCode, json.optString("en", ""))
                withContext(Dispatchers.Main) {
                    if (terms.isNotEmpty()) {
                        binding.tvTermsContent.text = terms
                    }
                }
            } catch (e: Exception) {
                Log.e("TermsOfService", "Failed to fetch from server", e)
                withContext(Dispatchers.Main) {
                    if (cached.isEmpty()) {
                        binding.tvTermsContent.text = TERMS_EN
                    }
                }
            }
        }
    }

    private fun getCachedTerms(langCode: String): String {
        val prefs = getSharedPreferences("terms_of_service", MODE_PRIVATE)
        return prefs.getString(langCode, "") ?: ""
    }

    companion object {
        private const val TERMS_EN = """Terms of Service

Last updated: February 2026

Please read these Terms of Service carefully before using the TripAI mobile application.

1. Acceptance of Terms

By downloading or using TripAI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the app.

2. Description of Service

TripAI is a mobile application that uses artificial intelligence to identify landmarks from photos and provide historical and cultural information. Features include:
- AI-powered landmark recognition
- Travel journal functionality
- Nearby places discovery
- Multi-language support
- Audio narration (paid plans)
- Share card generation (paid plans)

3. User Accounts

You may use TripAI as a guest or sign in with Google. You are responsible for maintaining the confidentiality of your account information and for all activities under your account.

4. Subscription Plans

TripAI offers free and paid subscription plans:
- Explorer (Free): 5 AI scans per day, basic features
- Traveler ($3.99/month): 50 AI scans per day, audio narration, share cards
- Globetrotter ($7.99/month): 200 AI scans per day, all features, priority processing

Subscriptions are billed monthly through Google Play. You may cancel anytime from your Google Play subscriptions settings.

5. Acceptable Use

You agree not to:
- Use the app for any unlawful purpose
- Upload inappropriate or harmful content
- Attempt to reverse engineer or hack the app
- Use the app to infringe on intellectual property rights

6. Intellectual Property

All content, features, and functionality of TripAI, including AI-generated descriptions, are owned by TripAI and protected by applicable intellectual property laws.

7. AI-Generated Content

Landmark information is generated by AI and may not always be accurate. We strive for accuracy but make no guarantees. Always verify important information from authoritative sources.

8. Limitation of Liability

TripAI is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the app.

9. Changes to Terms

We may update these Terms at any time. Continued use of the app after changes constitutes acceptance of the new Terms.

10. Contact Us

For questions about these Terms of Service, contact us at support@tripai.app"""
    }
}
